controller:
  enabled: false
agent:
  enabled: false
useLatestContainers: false
rbac:
  enabled: false
webhookConfiguration:
  enabled: false
custom:
  configuration:
    enabled: true
    name: http-range-switch # The name of akric
    capacity: 2
    discoveryHandlerName: http-discovery-switch # name of discovery handler, must be unique and matching discovery.name. will be used for socket creation
    discoveryDetails: |
      ipStart: 192.168.11.36
      ipEnd: 192.168.11.45
      applicationType: fmnist
    brokerPod:
      image:
        repository: gntouts/akri-example-broker
        tag: aba58b6
  discovery:
    enabled: true
    image:
      repository: harbor.nbfc.io/nubificus/iot/akri-discovery-handler-go
      tag: 4a42dab
    name: http-discovery-switch # name of discovery handler, must be unique and matching custom.configuration.discoveryHandlerName
