// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: discovery.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Specifies the type of endpoint.
type RegisterDiscoveryHandlerRequest_EndpointType int32

const (
	RegisterDiscoveryHandlerRequest_UDS     RegisterDiscoveryHandlerRequest_EndpointType = 0
	RegisterDiscoveryHandlerRequest_NETWORK RegisterDiscoveryHandlerRequest_EndpointType = 1
)

// Enum value maps for RegisterDiscoveryHandlerRequest_EndpointType.
var (
	RegisterDiscoveryHandlerRequest_EndpointType_name = map[int32]string{
		0: "UDS",
		1: "NETWORK",
	}
	RegisterDiscoveryHandlerRequest_EndpointType_value = map[string]int32{
		"UDS":     0,
		"NETWORK": 1,
	}
)

func (x RegisterDiscoveryHandlerRequest_EndpointType) Enum() *RegisterDiscoveryHandlerRequest_EndpointType {
	p := new(RegisterDiscoveryHandlerRequest_EndpointType)
	*p = x
	return p
}

func (x RegisterDiscoveryHandlerRequest_EndpointType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisterDiscoveryHandlerRequest_EndpointType) Descriptor() protoreflect.EnumDescriptor {
	return file_discovery_proto_enumTypes[0].Descriptor()
}

func (RegisterDiscoveryHandlerRequest_EndpointType) Type() protoreflect.EnumType {
	return &file_discovery_proto_enumTypes[0]
}

func (x RegisterDiscoveryHandlerRequest_EndpointType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisterDiscoveryHandlerRequest_EndpointType.Descriptor instead.
func (RegisterDiscoveryHandlerRequest_EndpointType) EnumDescriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{0, 0}
}

type RegisterDiscoveryHandlerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the `DiscoveryHandler`. This name is specified in an
	// Akri Configuration, to request devices discovered by this `DiscoveryHandler`.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Endpoint for the registering `DiscoveryHandler`
	Endpoint     string                                       `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	EndpointType RegisterDiscoveryHandlerRequest_EndpointType `protobuf:"varint,3,opt,name=endpoint_type,json=endpointType,proto3,enum=v0.RegisterDiscoveryHandlerRequest_EndpointType" json:"endpoint_type,omitempty"`
	// Specifies whether this device could be used by multiple nodes (e.g. an IP camera)
	// or can only be ever be discovered by a single node (e.g. a local USB device)
	Shared        bool `protobuf:"varint,4,opt,name=shared,proto3" json:"shared,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDiscoveryHandlerRequest) Reset() {
	*x = RegisterDiscoveryHandlerRequest{}
	mi := &file_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDiscoveryHandlerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDiscoveryHandlerRequest) ProtoMessage() {}

func (x *RegisterDiscoveryHandlerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDiscoveryHandlerRequest.ProtoReflect.Descriptor instead.
func (*RegisterDiscoveryHandlerRequest) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterDiscoveryHandlerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterDiscoveryHandlerRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *RegisterDiscoveryHandlerRequest) GetEndpointType() RegisterDiscoveryHandlerRequest_EndpointType {
	if x != nil {
		return x.EndpointType
	}
	return RegisterDiscoveryHandlerRequest_UDS
}

func (x *RegisterDiscoveryHandlerRequest) GetShared() bool {
	if x != nil {
		return x.Shared
	}
	return false
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{1}
}

type ByteData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vec           []byte                 `protobuf:"bytes,1,opt,name=vec,proto3,oneof" json:"vec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ByteData) Reset() {
	*x = ByteData{}
	mi := &file_discovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ByteData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByteData) ProtoMessage() {}

func (x *ByteData) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByteData.ProtoReflect.Descriptor instead.
func (*ByteData) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{2}
}

func (x *ByteData) GetVec() []byte {
	if x != nil {
		return x.Vec
	}
	return nil
}

type DiscoverRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// String containing all the details (such as filtering options)
	// the `DiscoveryHandler` needs to find a set of devices.
	DiscoveryDetails string `protobuf:"bytes,1,opt,name=discovery_details,json=discoveryDetails,proto3" json:"discovery_details,omitempty"`
	// list of Key-value pairs containing additional information
	// for the 'DiscoveryHandler' to discover devices
	DiscoveryProperties map[string]*ByteData `protobuf:"bytes,2,rep,name=discovery_properties,json=discoveryProperties,proto3" json:"discovery_properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	mi := &file_discovery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{3}
}

func (x *DiscoverRequest) GetDiscoveryDetails() string {
	if x != nil {
		return x.DiscoveryDetails
	}
	return ""
}

func (x *DiscoverRequest) GetDiscoveryProperties() map[string]*ByteData {
	if x != nil {
		return x.DiscoveryProperties
	}
	return nil
}

type DiscoverResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of discovered devices
	Devices       []*Device `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverResponse) Reset() {
	*x = DiscoverResponse{}
	mi := &file_discovery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResponse) ProtoMessage() {}

func (x *DiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResponse.ProtoReflect.Descriptor instead.
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{4}
}

func (x *DiscoverResponse) GetDevices() []*Device {
	if x != nil {
		return x.Devices
	}
	return nil
}

type Device struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier for this device
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Properties that identify the device. These are stored in the device's instance
	// and set as environment variables in the device's broker Pods. May be information
	// about where to find the device such as an RTSP URL or a device node (e.g. `/dev/video1`)
	Properties map[string]string `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optionally specify mounts for Pods that request this device as a resource
	Mounts []*Mount `protobuf:"bytes,3,rep,name=mounts,proto3" json:"mounts,omitempty"`
	// Optionally specify device information to be mounted for Pods that request this device as a resource
	DeviceSpecs   []*DeviceSpec `protobuf:"bytes,4,rep,name=device_specs,json=deviceSpecs,proto3" json:"device_specs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Device) Reset() {
	*x = Device{}
	mi := &file_discovery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Device) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Device) ProtoMessage() {}

func (x *Device) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Device.ProtoReflect.Descriptor instead.
func (*Device) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{5}
}

func (x *Device) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Device) GetProperties() map[string]string {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *Device) GetMounts() []*Mount {
	if x != nil {
		return x.Mounts
	}
	return nil
}

func (x *Device) GetDeviceSpecs() []*DeviceSpec {
	if x != nil {
		return x.DeviceSpecs
	}
	return nil
}

// From Device Plugin  API
// Mount specifies a host volume to mount into a container.
// where device library or tools are installed on host and container
type Mount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path of the mount within the container.
	ContainerPath string `protobuf:"bytes,1,opt,name=container_path,json=containerPath,proto3" json:"container_path,omitempty"`
	// Path of the mount on the host.
	HostPath string `protobuf:"bytes,2,opt,name=host_path,json=hostPath,proto3" json:"host_path,omitempty"`
	// If set, the mount is read-only.
	ReadOnly      bool `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Mount) Reset() {
	*x = Mount{}
	mi := &file_discovery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mount) ProtoMessage() {}

func (x *Mount) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mount.ProtoReflect.Descriptor instead.
func (*Mount) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{6}
}

func (x *Mount) GetContainerPath() string {
	if x != nil {
		return x.ContainerPath
	}
	return ""
}

func (x *Mount) GetHostPath() string {
	if x != nil {
		return x.HostPath
	}
	return ""
}

func (x *Mount) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

// From Device Plugin API
// DeviceSpec specifies a host device to mount into a container.
type DeviceSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Path of the device within the container.
	ContainerPath string `protobuf:"bytes,1,opt,name=container_path,json=containerPath,proto3" json:"container_path,omitempty"`
	// Path of the device on the host.
	HostPath string `protobuf:"bytes,2,opt,name=host_path,json=hostPath,proto3" json:"host_path,omitempty"`
	// Cgroups permissions of the device, candidates are one or more of
	// * r - allows container to read from the specified device.
	// * w - allows container to write to the specified device.
	// * m - allows container to create device files that do not yet exist.
	Permissions   string `protobuf:"bytes,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceSpec) Reset() {
	*x = DeviceSpec{}
	mi := &file_discovery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceSpec) ProtoMessage() {}

func (x *DeviceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceSpec.ProtoReflect.Descriptor instead.
func (*DeviceSpec) Descriptor() ([]byte, []int) {
	return file_discovery_proto_rawDescGZIP(), []int{7}
}

func (x *DeviceSpec) GetContainerPath() string {
	if x != nil {
		return x.ContainerPath
	}
	return ""
}

func (x *DeviceSpec) GetHostPath() string {
	if x != nil {
		return x.HostPath
	}
	return ""
}

func (x *DeviceSpec) GetPermissions() string {
	if x != nil {
		return x.Permissions
	}
	return ""
}

var File_discovery_proto protoreflect.FileDescriptor

const file_discovery_proto_rawDesc = "" +
	"\n" +
	"\x0fdiscovery.proto\x12\x02v0\"\xe6\x01\n" +
	"\x1fRegisterDiscoveryHandlerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12U\n" +
	"\rendpoint_type\x18\x03 \x01(\x0e20.v0.RegisterDiscoveryHandlerRequest.EndpointTypeR\fendpointType\x12\x16\n" +
	"\x06shared\x18\x04 \x01(\bR\x06shared\"$\n" +
	"\fEndpointType\x12\a\n" +
	"\x03UDS\x10\x00\x12\v\n" +
	"\aNETWORK\x10\x01\"\a\n" +
	"\x05Empty\")\n" +
	"\bByteData\x12\x15\n" +
	"\x03vec\x18\x01 \x01(\fH\x00R\x03vec\x88\x01\x01B\x06\n" +
	"\x04_vec\"\xf5\x01\n" +
	"\x0fDiscoverRequest\x12+\n" +
	"\x11discovery_details\x18\x01 \x01(\tR\x10discoveryDetails\x12_\n" +
	"\x14discovery_properties\x18\x02 \x03(\v2,.v0.DiscoverRequest.DiscoveryPropertiesEntryR\x13discoveryProperties\x1aT\n" +
	"\x18DiscoveryPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\"\n" +
	"\x05value\x18\x02 \x01(\v2\f.v0.ByteDataR\x05value:\x028\x01\"8\n" +
	"\x10DiscoverResponse\x12$\n" +
	"\adevices\x18\x01 \x03(\v2\n" +
	".v0.DeviceR\adevices\"\xe9\x01\n" +
	"\x06Device\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12:\n" +
	"\n" +
	"properties\x18\x02 \x03(\v2\x1a.v0.Device.PropertiesEntryR\n" +
	"properties\x12!\n" +
	"\x06mounts\x18\x03 \x03(\v2\t.v0.MountR\x06mounts\x121\n" +
	"\fdevice_specs\x18\x04 \x03(\v2\x0e.v0.DeviceSpecR\vdeviceSpecs\x1a=\n" +
	"\x0fPropertiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"h\n" +
	"\x05Mount\x12%\n" +
	"\x0econtainer_path\x18\x01 \x01(\tR\rcontainerPath\x12\x1b\n" +
	"\thost_path\x18\x02 \x01(\tR\bhostPath\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\"r\n" +
	"\n" +
	"DeviceSpec\x12%\n" +
	"\x0econtainer_path\x18\x01 \x01(\tR\rcontainerPath\x12\x1b\n" +
	"\thost_path\x18\x02 \x01(\tR\bhostPath\x12 \n" +
	"\vpermissions\x18\x03 \x01(\tR\vpermissions2\\\n" +
	"\fRegistration\x12L\n" +
	"\x18RegisterDiscoveryHandler\x12#.v0.RegisterDiscoveryHandlerRequest\x1a\t.v0.Empty\"\x002K\n" +
	"\x10DiscoveryHandler\x127\n" +
	"\bDiscover\x12\x13.v0.DiscoverRequest\x1a\x14.v0.DiscoverResponse0\x01B7Z5github.com/nubificus/akri-discovery-handler-go/pkg/pbb\x06proto3"

var (
	file_discovery_proto_rawDescOnce sync.Once
	file_discovery_proto_rawDescData []byte
)

func file_discovery_proto_rawDescGZIP() []byte {
	file_discovery_proto_rawDescOnce.Do(func() {
		file_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_discovery_proto_rawDesc), len(file_discovery_proto_rawDesc)))
	})
	return file_discovery_proto_rawDescData
}

var file_discovery_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_discovery_proto_goTypes = []any{
	(RegisterDiscoveryHandlerRequest_EndpointType)(0), // 0: v0.RegisterDiscoveryHandlerRequest.EndpointType
	(*RegisterDiscoveryHandlerRequest)(nil),           // 1: v0.RegisterDiscoveryHandlerRequest
	(*Empty)(nil),                                     // 2: v0.Empty
	(*ByteData)(nil),                                  // 3: v0.ByteData
	(*DiscoverRequest)(nil),                           // 4: v0.DiscoverRequest
	(*DiscoverResponse)(nil),                          // 5: v0.DiscoverResponse
	(*Device)(nil),                                    // 6: v0.Device
	(*Mount)(nil),                                     // 7: v0.Mount
	(*DeviceSpec)(nil),                                // 8: v0.DeviceSpec
	nil,                                               // 9: v0.DiscoverRequest.DiscoveryPropertiesEntry
	nil,                                               // 10: v0.Device.PropertiesEntry
}
var file_discovery_proto_depIdxs = []int32{
	0,  // 0: v0.RegisterDiscoveryHandlerRequest.endpoint_type:type_name -> v0.RegisterDiscoveryHandlerRequest.EndpointType
	9,  // 1: v0.DiscoverRequest.discovery_properties:type_name -> v0.DiscoverRequest.DiscoveryPropertiesEntry
	6,  // 2: v0.DiscoverResponse.devices:type_name -> v0.Device
	10, // 3: v0.Device.properties:type_name -> v0.Device.PropertiesEntry
	7,  // 4: v0.Device.mounts:type_name -> v0.Mount
	8,  // 5: v0.Device.device_specs:type_name -> v0.DeviceSpec
	3,  // 6: v0.DiscoverRequest.DiscoveryPropertiesEntry.value:type_name -> v0.ByteData
	1,  // 7: v0.Registration.RegisterDiscoveryHandler:input_type -> v0.RegisterDiscoveryHandlerRequest
	4,  // 8: v0.DiscoveryHandler.Discover:input_type -> v0.DiscoverRequest
	2,  // 9: v0.Registration.RegisterDiscoveryHandler:output_type -> v0.Empty
	5,  // 10: v0.DiscoveryHandler.Discover:output_type -> v0.DiscoverResponse
	9,  // [9:11] is the sub-list for method output_type
	7,  // [7:9] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_discovery_proto_init() }
func file_discovery_proto_init() {
	if File_discovery_proto != nil {
		return
	}
	file_discovery_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_discovery_proto_rawDesc), len(file_discovery_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_discovery_proto_goTypes,
		DependencyIndexes: file_discovery_proto_depIdxs,
		EnumInfos:         file_discovery_proto_enumTypes,
		MessageInfos:      file_discovery_proto_msgTypes,
	}.Build()
	File_discovery_proto = out.File
	file_discovery_proto_goTypes = nil
	file_discovery_proto_depIdxs = nil
}
